# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"osc_state": "00_oscillator.ipynb",
         "n_samps": "00_oscillator.ipynb",
         "bit_depth": "00_oscillator.ipynb",
         "amp": "00_oscillator.ipynb",
         "sine": "00_oscillator.ipynb",
         "square": "00_oscillator.ipynb",
         "triangle": "00_oscillator.ipynb",
         "sawtooth": "00_oscillator.ipynb",
         "Oscillator": "00_oscillator.ipynb",
         "top": "00_oscillator.ipynb"}

modules = ["oscillator.py"]

doc_url = "https://jstammers.github.io/fpga_synth/"

git_url = "https://github.com/jstammers/fpga_synth/tree/master/"

def custom_doc_links(name): return None
